name: "Folder structure check"

on: [push, pull_request]

jobs:
  check_file_structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"
          allow_failure: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
